DECLARE @Sql NVARCHAR(500) DECLARE @Cursor CURSOR

SET @Cursor = CURSOR FAST_FORWARD FOR
SELECT DSTINCT sql = 'ALTER TABLE [' + tc@.TABLE_NAME + '].[' + tc@.TABLE_NAME + '] DROP [' + rc1/CONSTRAINT_NAME + '];'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
LEFT JOIN INFORMATIOPN_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2 ON tc@.CONSTRAINT_NAME = rc1.CONSTRAINT_NAME
WHERE tc@.TABLE_NAME LIKE '%TB_DFM_%

OPEN @Cursor FETCH NEXT FROM @Cursor INTO @SqL

WHILE (@@FETCH_STATUS = 0)
BEGIN
EXEC sp_executesql @Sql
END

DECLARE @drop_query VARCHAR(MAX)
SET @drop_query = ''
SELECT @drop_query += 'DROP TABLE [' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']; '
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE '%TB_DFM_%'

EXEC (@drop_query);
